<?php

########################################################################
# Extension Manager/Repository config file for ext: "bxslider"
#
# Auto generated by Extension Builder 2014-02-03
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'bxSlider',
	'description' => 'bxSlider ★ TYPO3 Slider Plugin with various settings ★ Responsive jQuery Content Slider',
	'category' => 'plugin',
	'author' => 'Maxim Bidiuk',
	'author_email' => 'maxim@jcmedia.de',
	'author_company' => 'JCMedia Internetagentur GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>